### ISSUE TITLE
Incorrect uptime displayed 

### ISSUE THREAD

**Issue by joshua-pe** [rpolenthon/homemanagerapp#1]
Incorrect uptime.

Using homebridge (not hoobs) and the uptime is incorrect. Any ideas?

**Comment by rpolenthon** [comment]
Hi,

sorry for my delayed response. Missed the notification.

The uptime is system time related. So please make sure that the timezone of your server is the same as on your phone.

Please let me know if that fixed the issue ;)

Cheers,
Ron
