### ISSUE TITLE
Add ability to duplicate accessory 

### ISSUE THREAD

**Issue by NeighNeighNeigh** [rpolenthon/homemanagerapp#2]
I have many accessories configured as part of the Broadlink RM platform. It would be wonderful if I could duplicate an entry rather than having to manually build from scratch.
![46FCE817-D7BE-4203-A85F-44DE8978CE5F](https://user-images.githubusercontent.com/4795315/96516021-13c3a680-12b2-11eb-8ca8-b0cfa24accf5.jpeg)

**Comment by rpolenthon** [comment]
Hi, I added the option to duplicate config elements in Homemanager 3, available as public beta soon. If you want you can already pre sign up here: https://forms.gle/mMtPvm9uPbZEaJat8
